services:
  portfolio:
    build: .
    container_name: david-portfolio
    ports:
      - "5000:5000"

    env_file:
      - .env

    volumes:
      - ./instance:/app/instance
      - ./static/uploads:/app/static/uploads

    restart: unless-stopped